# Generated by Django 2.2 on 2020-10-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=225)),
                ('numero_de_telephone', models.IntegerField(max_length=20)),
                ('biographie', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'employers',
            },
        ),
    ]
