# Generated by Django 2.2 on 2020-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201002_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'employer'},
        ),
        migrations.AlterField(
            model_name='employer',
            name='numero_de_telephone',
            field=models.CharField(max_length=255),
        ),
    ]
